name: 'PlatformIO Dependabot'
description: 'a Dependabot like script for PlatformIO'
inputs:
  github_token:
    description: 'Github Token'
    required: true
  assignee:
    description: 'Who to assign the pull request'
    required: false
  project_path:
    description: 'Path to PlatformIO Project. Default: current root dir'
    required: false
  rsa:
    description: 'RSA'
    required: true
  rsa_pub:
    description: 'RSA public'
    required: true
runs:
  steps:
    - run: |
        mkdir -p $HOME/.ssh
        echo "${{ inputs.id_rsa }}" > $HOME/.ssh/id_rsa
        chmod 400 $HOME/.ssh/id_rsa
        echo "${{ inputs.id_rsa_pub }}" > $HOME/.ssh/id_rsa.pub
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.assignee }}
    - ${{ inputs.project_path }}
  entrypoint: "/app/entrypoint.sh"
